apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label of pod 
    run: ashuweb111
  name: ashuweb111 # name of pod 
spec:
  imagePullSecrets: # to call secrets 
  - name: ocrsec # name of secret under current namespace 
  containers:
  - image: phx.ocir.io/axmbtg8judkl/oraclewebapp:v1 # image from OCR 
    name: ashuweb111
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
